version: '3'
services:
  maxkb:
    image: harbor.uat.enflame.cc/library/enflame.cn/maxkb:1.2
    container_name: maxkb
    ports:
      - 18080:8080
    volumes:
      - ../volumes/maxkb:/var/lib/postgresql/data
      - /root/share_models/local_embedding/:/opt/maxkb/model/local_embedding/
    privileged: true
