version: '3'
services:
  maxkb:
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_maxkb:1.0
    container_name: maxkb
    ports:
      - 18080:8080
    volumes:
      - ../volumes/maxkb:/var/lib/postgresql/data
      - /root/share_models/local_embedding/:/opt/maxkb/model/local_embedding/
    privileged: true
